# Generated by Django 5.0.2 on 2024-03-10 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arithmetic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number1', models.FloatField(verbose_name='Перше число')),
                ('number2', models.FloatField(verbose_name='Друге число')),
                ('operation', models.TextField(verbose_name='Оператор')),
            ],
            options={
                'verbose_name': 'Арифметичні операції',
                'verbose_name_plural': 'Арифметична операція',
            },
        ),
        migrations.CreateModel(
            name='Conversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kilometers', models.FloatField(verbose_name='Кілометри')),
            ],
            options={
                'verbose_name': 'Кілометрів',
                'verbose_name_plural': 'Кілометри',
            },
        ),
        migrations.DeleteModel(
            name='Division',
        ),
    ]
